4. Маршрут по тайным тропам
htmlacademy-react/170610-what-to-watch-6 pull request #4
Opened 2021-02-06 09:12 UTC by avedmigen

2021-02-07 14:55 UTC, ElseeCCD requested changes

2021-02-07 14:55 UTC, ElseeCCD commented on src/components/add-review-screen/add-review-screen.jsx
> +  const films = movies;
передача по ссылке. Для чего?

2021-02-07 14:55 UTC, ElseeCCD commented on src/components/add-review-screen/add-review-screen.jsx
> +  const id = parseInt(props.match.params.id, 10);
это ты так строку к числу приводишь?

2021-02-07 14:55 UTC, ElseeCCD commented on src/components/movie-page-screen/movie-page-screen.jsx
> +  const films = movies;
снова непонятная передача по ссылке )

2021-02-07 14:55 UTC, ElseeCCD commented on src/components/player-screen/player-screen.jsx
> +  const movie = findObjInArrayById(films, id);
меня очень смущает этот накопированный код )

2021-02-07 14:55 UTC, ElseeCCD commented on src/components/player-screen/player-screen.jsx
> +    }
Так, тут заменить нужно тернарником (`... ? ... : ...`) и написать всю функцию в одну строку. И, кстати, это функция :) в названии функции должен быть глагол :)

2021-02-07 14:55 UTC, ElseeCCD commented on src/types.js
> +export const objectPropType = PropTypes.object;
Не пойдет. Во-первых, бессмысленно выносить в константу `PropTypes.object`. Во-вторых, нужно расписывать все сложные структуры

2021-02-07 15:57 UTC, avedmigen commented on src/components/add-review-screen/add-review-screen.jsx
> +  const films = movies;
Сначала была попытка деструктуризации. Потом забыл исправить конструкцию. Исправлено.

2021-02-07 15:57 UTC, avedmigen commented on src/components/add-review-screen/add-review-screen.jsx
> +  const id = parseInt(props.match.params.id, 10);
Исправлено на Number

2021-02-07 16:02 UTC, avedmigen commented on src/components/movie-page-screen/movie-page-screen.jsx
> +  const films = movies;
Исправлено.  Аналогичная проблема https://github.com/htmlacademy-react/170610-what-to-watch-6/pull/4#discussion_r571638313

2021-02-07 16:04 UTC, avedmigen commented on src/components/player-screen/player-screen.jsx
> +  const movie = findObjInArrayById(films, id);
Убрал ссылку, добавил функцию. 

`  const id = getIdFromRouteProps(props);
  const movie = findObjInArrayById(movies, id);`

Стало покороче. Но все равно не DRY.  Как улучшить?

2021-02-07 16:07 UTC, avedmigen commented on src/components/player-screen/player-screen.jsx
> +    }
Исправлено.

2021-02-07 16:50 UTC, avedmigen commented on src/types.js
> +export const objectPropType = PropTypes.object;
Исправил. Валидацию пропсов Роута оставил как объект, расписывать не стал. Т.к. это передает браузер, а не программист - что-то другое там никогда не придёт.  Поля промо-фильма валидирую МувиШейпом. Они одинаковые.

2021-02-08 07:32 UTC, ElseeCCD commented on src/components/player-screen/player-screen.jsx
> +  const movie = findObjInArrayById(films, id);
Чуть позже вы улучшите это дело ) Всё поступенно ) Но в функцию можно было не выносить.

2021-02-08 07:48 UTC, ElseeCCD commented on src/types.js
> +export const objectPropType = PropTypes.object;
Нет, передаёт не браузер, передаёт react-router-dom ) Можно сделать хотя бы по аналогии вот с этим: https://reactrouter.com/core/api/withRouter

2021-02-08 07:48 UTC, merged

2021-02-08 08:15 UTC, avedmigen commented on src/types.js
> +export const objectPropType = PropTypes.object;
Понял, доделаю в новой домашке. Спасибо.

2021-02-11 12:49 UTC, avedmigen commented on src/types.js
> +export const objectPropType = PropTypes.object;
Исправлено.