5. Обратная сторона реальности
htmlacademy-react/170610-what-to-watch-6 pull request #5
Opened 2021-02-11 13:06 UTC by avedmigen

2021-02-11 18:45 UTC, ElseeCCD requested changes

2021-02-11 18:45 UTC, ElseeCCD commented on markup/movie-page-reviews.html
> +                    <p class="review__text">Discerning travellers and Wes Anderson fans will luxuriate in the glorious Mittel-European kitsch of one of the director's funniest and most exquisitely de
почто разметку правишь? ))

2021-02-11 18:45 UTC, ElseeCCD commented on src/components/add-review-screen/add-review-screen.jsx
> +    if (checkEvtClassName(evt, `rating__input`) || checkEvtClassName(evt, `add-review__textarea`)) {
это очень подозрительный код. Зачем классы какие-то проверяешь?

2021-02-11 18:45 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +  const [activeMovieId, setActiveMovieId] = useState({});
Почему называется состояние `activeMovieId`, а хранится в нём объект? id - это обычно строка какая-нибудь

2021-02-11 18:45 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +    setActiveMovieId(Object.assign(activeMovieId, movie));
для чего тут `Object.assign`? Зачем сливать эти объекты?

2021-02-11 18:45 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +          key={movie + i}
В movie разве не объект хранится? Кажется, у тебя key будут формата `[object Object]1`, `[object Object]2`...
У тебя же есть айдишники у фильмов, они должны быть уникальными, используй их

2021-02-11 18:45 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +    evt.preventDefault();
а какое поведение по умолчанию тут нужно prevent? )

2021-02-11 18:45 UTC, ElseeCCD commented on src/mocks/reviews.js
> +export default reviews;
как у тебя отзывы и фильмы соотносятся?

2021-02-11 18:45 UTC, ElseeCCD commented on src/utils.js
> +export const renameDashedAttribute = (attr) => {
давай чуть переименуем: `converDashToCamelCase`, например. Тогда сразу понятно, что и куда конвертируем. И название аргумента переделай, универсальная же функция получается, зачем её только к аттрибутам применять, когда можно к чему угодно?

2021-02-12 05:56 UTC, avedmigen commented on markup/movie-page-reviews.html
> +                    <p class="review__text">Discerning travellers and Wes Anderson fans will luxuriate in the glorious Mittel-European kitsch of one of the director's funniest and most exquisitely de
сам не знаю, как и зачем это я сделал :))) вернул мувиз в маркап

2021-02-12 05:58 UTC, avedmigen commented on src/components/add-review-screen/add-review-screen.jsx
> +    if (checkEvtClassName(evt, `rating__input`) || checkEvtClassName(evt, `add-review__textarea`)) {
исправлено.

2021-02-12 06:00 UTC, avedmigen commented on src/components/movies-list/movies-list.jsx
> +  const [activeMovieId, setActiveMovieId] = useState({});
сначала думал айди хранить, потом передумал на целый объект. а имя осталось... исправлено

2021-02-12 06:01 UTC, avedmigen commented on src/components/movies-list/movies-list.jsx
> +    setActiveMovieId(Object.assign(activeMovieId, movie));
исправил, но прошу после коммита проверить насколько это оптимальный синтаксис. не уверен.

2021-02-12 06:32 UTC, avedmigen commented on src/components/movies-list/movies-list.jsx
> +          key={movie + i}
Я тоже про этот странный [object Object] думал, но исправить не получилось. Сейчас вроде заработало. Исправлено

2021-02-12 06:33 UTC, avedmigen commented on src/components/movies-list/movies-list.jsx
> +    evt.preventDefault();
Пихать везде evt.preventDefault(); - это поведение по умолчанию юного программиста, который писал этот код :))) Исправлено

2021-02-12 06:38 UTC, avedmigen commented on src/mocks/reviews.js
> +export default reviews;
перенес код моков отзывов в файл с моками фильмов

2021-02-12 06:40 UTC, avedmigen commented on src/utils.js
> +export const renameDashedAttribute = (attr) => {
Исправил. Теперь convertDashedToCamelCase

2021-02-12 15:34 UTC, ElseeCCD approved these changes

2021-02-12 15:34 UTC, ElseeCCD commented on src/components/small-movie-card/small-movie-card.jsx
> +        (evt) => {
ну тут можно вообще evt не передавать, раз он использоваться не будет.

2021-02-12 15:35 UTC, merged

2021-02-12 15:43 UTC, avedmigen commented on src/utils.js
> +export const renameDashedAttribute = (attr) => {
Да, точно. Исправлю в следующем коммите. Спасибо

2021-02-22 14:31 UTC, avedmigen commented on src/components/small-movie-card/small-movie-card.jsx
> +        (evt) => {
исправлено