6. Больше подробностей (часть 1)
htmlacademy-react/170610-what-to-watch-6 pull request #6
Opened 2021-02-22 14:33 UTC by avedmigen

2021-02-23 17:41 UTC, ElseeCCD requested changes

2021-02-23 17:41 UTC, ElseeCCD commented on src/components/movies-list/movies-list.jsx
> +  const [isActiveMovie, setActiveMovie] = useState(false);
когда называем что-то, начиная с `is` подразумевается, что там будет булево значение, что ты изначально и задаешь, но ниже же перезаписываешь значение через `setActiveMovie`, передаешь туда `movie`, который совершенно точно не boolean

2021-02-23 17:41 UTC, ElseeCCD commented on src/components/small-movie-card/small-movie-card.jsx
> +  const {id, name, previewImage, posterImage, videoLink} = movie;
В компоненте `MoviesList`  ты передаешь сюда пропс `isActiveMovie`, но тут не принимаешь. Для чего он тогда? Ты всю логику по запуску плеера инкапсулировал внутри карточки фильма и видеоплеера, удали лишнее

2021-02-23 17:41 UTC, ElseeCCD commented on src/components/small-movie-card/small-movie-card.jsx
> +            posterImage = {posterImage}
сюда нужно передавать previewImage. У тебя не должно быть никакого визуального отклика при наведении на карточку, только через секунду. А то так при наведении уже картинки скачут, не надо так

2021-02-23 17:41 UTC, ElseeCCD commented on src/components/small-movie-card/small-movie-card.jsx
> +  const [startPlayer, setStartPlayer] = useState(false);
вот здесь как раз нужно назвать переменную с `is`. Например `isPlayerStarted`

2021-02-26 06:50 UTC, avedmigen commented on src/components/movies-list/movies-list.jsx
> +  const [isActiveMovie, setActiveMovie] = useState(false);
понял. спасибо, исправлено

2021-02-26 06:52 UTC, avedmigen commented on src/components/small-movie-card/small-movie-card.jsx
> +  const {id, name, previewImage, posterImage, videoLink} = movie;
согласен, исправлено

2021-02-26 07:00 UTC, avedmigen commented on src/components/small-movie-card/small-movie-card.jsx
> +            posterImage = {posterImage}
я исправил, но теперь пропал постер. по идее именно он должен показываться перед тем, как стартует маленькое видео. постер это не превью, это другая картинка.

2021-02-26 07:02 UTC, avedmigen commented on src/components/small-movie-card/small-movie-card.jsx
> +  const [startPlayer, setStartPlayer] = useState(false);
спасибо, исправлено

2021-02-26 08:03 UTC, ElseeCCD approved these changes

2021-02-26 08:03 UTC, merged